### ISSUE TITLE
Add Input Validation to Login and Signup Pages

### ISSUE THREAD

**Issue by abdullahqaisar** [abdullahqaisar/sehatchain#4]
### **Overview:**

The login and signup pages of our application are vital components for user authentication and registration. To enhance user experience and ensure data integrity, we need to implement input validation to validate user-provided information before it is processed. This will help prevent common issues such as incorrect email formats, weak passwords, and other invalid data entries.

### **Proposed Changes:**

    Add client-side input validation to the login and signup forms.
    Implement checks for email format, password strength, and any other relevant fields.
    Display informative error messages to users when validation fails.
    Ensure that the server-side code also validates the input to provide an additional layer of security.

### **Benefits:**

    Improved User Experience: Input validation will provide immediate feedback to users, reducing frustration due to invalid inputs.
    Data Integrity: Prevent incorrect or harmful data from entering the system.
    Enhanced Security: Validation helps protect against potential security threats and vulnerabilities.

### **Tasks for a Beginner:**

This issue is beginner-friendly and provides a great opportunity to get started with our project. Here are the tasks you can work on:

    **Client-side Validation:**
        Review the login and signup forms in the codebase.
        Add JavaScript validation code to these forms. You can use HTML5 attributes and JavaScript functions for this purpose.
        Implement checks for email format, password strength, and any other fields that require validation.

    **Use Joi for Validation:**
        Incorporate the Joi library for input validation. You can find Joi documentation and resources [here](https://joi.dev/).

    **Error Messages:**
        Customize and display informative error messages when validation fails.
        Ensure that the error messages are user-friendly and guide users on how to correct their input.

    Server-side Validation (Optional):
        If you're comfortable with server-side code, consider implementing server-side validation using Joi to provide an additional layer of security.

### **Guidance:**

    Take a look at our existing codebase to understand how the login and signup forms are structured.
    Utilize the Joi library to streamline the validation process and ensure that it aligns with best practices.
    Test the login and signup pages thoroughly to confirm that validation works as expected.
    Follow coding and naming conventions used in the project to maintain code consistency.

### **Contributions and Collaboration:**

Feel free to ask questions and seek guidance from the project team if you encounter any issues or need assistance during the implementation. We encourage collaboration, and this issue is a great starting point for contributing to our project.

**Comment by jepoy92** [comment]
Hello, id like to be assigned to this issue!

**Comment by abdullahqaisar** [comment]
Sure, assigning this to you.
