### ISSUE TITLE
Find and Remove console.log() from Backend

### ISSUE THREAD

**Issue by abdullahqaisar** [abdullahqaisar/sehatchain#6]
### Overview:

Our backend code currently includes console.log() statements, which are used for debugging and logging purposes. These statements, while helpful during development, should not be present in the production code. We need to identify and remove all instances of console.log() from our backend codebase.

### Proposed Changes:

    Search the backend codebase for all occurrences of console.log().
    Replace or remove these statements to ensure they are not executed in the production environment.

### Benefits:

    Improved Code Cleanliness: Removing unnecessary console.log() statements enhances the clarity and cleanliness of our production code.
    Prevents Unintended Debug Output: Removing these statements ensures that debug information is not inadvertently exposed in a production environment.

### Tasks for a Contributor:

This issue is suitable for contributors who want to make a codebase more production-ready:

    Identify console.log():
        Review the backend codebase to locate and list all instances of console.log().

    Modify or Remove Statements:
        Replace console.log() with appropriate logging methods or remove them altogether.

Contributions and Collaboration:

If you have questions or need guidance while working on this issue, please feel free to ask for assistance from the project team. Your contributions to clean up the backend code are greatly appreciated.

**Comment by twong17** [comment]
Hey @abdullahqaisar could you assign this one to me please?

**Comment by abdullahqaisar** [comment]
Sure, assigned this to you. 

I was setting up the repository for contributions right now, its not complete yet. Please let me know if you face any issues in running it.

**Comment by smrkhan21** [comment]
Hey @abdullahqaisar, if it is not fixed yet, could you assign this one to me please?

**Comment by abdullahqaisar** [comment]
Hey @smrkhan21, this is already being worked on. Could you please look for another issue to work on?

Thanks
